server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php index.html;

    client_max_body_size 20M;

    # Tiempo suficiente para generar y descargar respaldos
    client_header_timeout 600s;
    client_body_timeout 600s;
    send_timeout 600s;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass app:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 600s;
        fastcgi_read_timeout 600s;
    }

    location ~ /\.ht {
        deny all;
    }
}